name: ✨Feature Request
description: Request a new feature or enhancement.
labels: ["enhancement"]
title: "[FEAT]: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
  
  - type: checkboxes
    id: new-feature
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for this project.
      options:
      - label: I have searched the existing features
        required: true
      
  - type: textarea
    id: feature-description
    attributes:
      label: Description of feature
      description: Give us a brief description of the feature or enhancement you would like to see added.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
